language: node_js
node_js:
- '6'
before_install: npm install -g grunt-cli
install: npm install
before_script: grunt
notifications:
  slack:
    secure: r1U8Xkv85VcZfrcZ1QLAUcno7Myo21hGg+F+VgXTYj6/oK4oq/jHKyNzRUS9cXKj8p5eh6I1uZk8ma//TceQexeIHnv26j66E989PAx9WryRSSjGOKUCf6ZjYW4aQqeBSDCUsRm09a3RpVNIdW9zwWtvPKmYtfhvCgtMgYs3jI3cGYQbLNRKJSzVLuhLDL1IdrQjffbncps54JuVwBA4owy7Na6QUjU0X6N/jdjhorKKvAHKYcDKicq8SRdyzP35sou8xB8Tlc2evbcyujFfhGVBN1SA6rlBjJWsF3dXrbuHduNp66z6v/oJ7QGBmRvdETAdUdi2rRileSvONpUvwjYxmQUFU8LItB0QvkhKQ3ORppKQlruGHDXw0qBU6zNzaIGiJt7o+hGt+gBKajDwzCkVBXhqH9PO/rhDbMrpktvvqH3NOCKccb2eiWiCpxfmrOwKsy34cdNIbeplpAyK3Yxl5GzgLGsnTJ6mJtF5MM25qycUaefMj6rK0nJFFV5lj44toSP5dYKFFMcRihZXg206imePQusBYpO98bw9bpIc85sze1HxEY5IoLk4FCFMpC1Q0w3C1mtlRooIhGWZKo18ZOKruHKjERpUXCIPpy4DzwdLf/vfXPYoKXaGDh7+hzTEuWDTcVyG7B/KyAqVbL/XqOd1MBTfB596IsDBF3w=
